EXPERIMENT_NAME: 'rigid_to_real/source_only'
NUM_WORKERS: 8
DEVICE: 'cuda'
MODEL:
  WEIGHTS: ''
  TEACHER_WEIGHTS: ''
SOLVER:
  BATCH_SIZE: 4
  NUM_EPOCHS: 260
  LEARNING_RATE: 0.001
  SCHEDULER: 'multistep'
  LR_LAMBDA: 0.1
  LR_MILESTONES: [180, 240]
  CHECKPOINT_INTERVAL: 20
  LOSS_FACTOR: 10.
DA:
  MT_TEACHERALPHA: 0.996
INPUT:
  NUM_POINTS_SMALL: 8192
  NUM_POINTS_LARGE: 16384
  SCALE_NORM_FACTOR: 100
AUGMENTATIONS:
  METHOD: 'rigid'
  RANDOM_SEED: -1
  MAX_ROTATION_ANGLE: 10.
  MAX_SCALE_OFFSET: 0.1
  MAX_TRANSLATION: 0.005
